parameters:
    hello_world: "Hello world!"

services:    
    product_repository:
        class: EcotaxPatch\Repository\ProductRepository
        arguments: ['@doctrine.dbal.default_connection', '%database_prefix%']
